Add alpha keyboard remapping.

diff --git a/enveloppe b/enveloppe
--- a/enveloppe
+++ b/enveloppe
@@ -1,5 +1,18 @@
 #!/bin/sh
 
+# Args
+ARGS=("$@")
+ELEMENTS=${#ARGS[@]}
+for (( i=0;i<$ELEMENTS;i++)); do
+    if  [ "${ARGS[${i}]}" == "exit" ] || \
+	[ "${ARGS[${i}]}" == "quit" ]; then
+	    exit_enveloppe=true
+    fi;
+    if  [ "${ARGS[${i}]}" == "dep" ]; then
+	install_dep=true
+    fi;
+done
+
 # Colors
 RED=$(tput setaf 1)
 GREEN=$(tput setaf 2)
@@ -15,21 +28,56 @@ DIM=$(tput dim)
 # Editor
 editors=("nvim" "vim" "vi" "emacs" "nano" "ed")
 for e in "${editors[@]}"; do
-	if [ "$(which "$e" 2>/dev/null)" ]; then EDITOR="$e" && break; fi
+    if [ "$(which "$e" 2>/dev/null)" ]; then EDITOR="$e" && break; fi
 done
+if [ -z "$EDITOR" ]; then echo "${BOLD}${YELLOW}[info] could not find an editor.${RESET}"; fi
 
 # Aliases
 alias 	la="ls -a"  \
-	ll="ls -l"  \
-	v="$EDITOR" \
-	e="$EDITOR" \
-	sv="sudo $EDITOR" \
-	se="sudo $EDITOR" \
-	SS="sudo systemctl" \
-	dc="docker-compose" \
-	:q="exit"
+    ll="ls -l"  \
+    v="$EDITOR" \
+    e="$EDITOR" \
+    sv="sudo $EDITOR" \
+    se="sudo $EDITOR" \
+    SS="sudo systemctl" \
+    dc="docker-compose" \
+    :q="exit"
 
 # Prompt
 export PS1="\[${BOLD}\]\[${RED}\][\[${YELLOW}\]\u\[${GREEN}\]@\[${BLUE}\]\h \[${MAGENTA}\]\W\[${RED}\]]\[${WHITE}\]\\$ \[${RESET}\]"
+
+# Keyboard remaps
+kb_deps=("setxkbmap" "xmodmap" "xset" "xcape")
+for d in ${kb_deps[@]}; do
+    if ! [[ $(which "$d" 2>/dev/null) ]]; then
+	if [ -z "$install_dep" ]; then
+	    echo "${BOLD}${RED}[info]$ keyboard cannot remap (missing \"$d\").${RESET}"
+	    cannot_remap=true
+	else
+	    echo "TODO: install dependencies"
+	fi
+    fi
+done
+
+remap_kb() {
+    setxkbmap -option 'ctrl:nocaps' 	     # Replace CapsLock by Control
+    setxkbmap -option "shift:both_capslock"  # Press Shift_L and Shift_R for CapsLock
+    spare_modifier="Super_L" 		     # (1a) Map ESC to Super_L when held (else, normal ESC)
+    xmodmap -e "keycode 9 = $spare_modifier" # (1b) (keycode 9 is ESC)
+    xmodmap -e "keycode any = Escape" 	     # (1c)
+    xmodmap -e 'keycode 49 = Super_R'        # Remap "twosuperior" when in AZERTY
+    xset r rate 220 50                       # Typing speed repeat.
+    killall xcape 2>/dev/null ; xcape -e 'Super_R=Escape;Super_L=Escape' # Single MOD press = ESC
+    xcape -e 'Control_L=Escape' # Single Ctrl press = ESC
+}
+
+unmap_kb() {
+    setxkbmap -option
+    echo "${BOLD}${GREEN}[info]${DIM} keyboard default reset.${RESET}"
+}
+
+if [ -z "$cannot_remap" ]; then
+    if [ -z "$exit_enveloppe" ]; then remap_kb; else unmap_kb; fi
+fi
 
 echo "${BOLD}${BLUE}en[v]eloppe successfully sourced.${RESET}"
